const verbs = {
  abrir: {
    translation: "To Open",
    past: {
      el: "abrió",
      tu: "abriste",
      nosotros: "abrimos",
      ustedes: "abrieron",
      yo: "abrí",
    },
    pres: {
      el: "abre",
      nosotros: "abrimos",
      tu: "abres",
      ustedes: "abren",
      yo: "abro",
    },
    futur: {
      el: "abrirá",
      nosotros: "abriremos",
      tu: "abrirás",
      ustedes: "abrirán",
      yo: "abriré",
    },
    imperf: {
      nosotros: "abríamos",
      tu: "abrías",
      ustedes: "abrían",
      yo: "abría",
      el: "abrío",
    },
  },
  acabar: {
    translation: "To finish",
    past: {
      el: "acabó",
      tu: "acabaste",
      ustedes: "acabaron",
      nosotros: "acabamos",
      yo: "acabé",
    },
    pres: {
      el: "acaba",
      nosotros: "acabamos",
      tu: "acabas",
      ustedes: "acaban",
      yo: "acabo",
    },
    futur: {
      el: "acabará",
      nosotros: "acabaremos",
      tu: "acabarás",
      ustedes: "acabarán",
      yo: "acabaré",
    },
    imperf: {
      nosotros: "acabábamos",
      tu: "acababas",
      el: "acababa",
      ustedes: "acababan",
      yo: "acababa",
    },
  },
  ayudar: {
    translation: "To help",
    past: {
      el: "ayudó",
      tu: "ayudaste",
      nosotros: "ayudamos",
      ustedes: "ayudaron",
      yo: "ayudé",
    },
    pres: {
      el: "ayuda",
      nosotros: "ayudamos",
      tu: "ayudas",
      ustedes: "ayudan",
      yo: "ayudo",
    },
    futur: {
      el: "ayudará",
      nosotros: "ayudaremos",
      tu: "ayudarás",
      ustedes: "ayudarán",
      yo: "ayudaré",
    },
    imperf: {
      nosotros: "ayudábamos",
      tu: "ayudabas",
      ustedes: "ayudaban",
      el: "ayudaba",
      yo: "ayudaba",
    },
  },
  bailar: {
    translation: "To dance",
    past: {
      el: "bailó",
      tu: "bailaste",
      ustedes: "bailaron",
      nosotros: "bailamos",
      yo: "bailé",
    },
    pres: {
      el: "baila",
      nosotros: "bailamos",
      tu: "bailas",
      ustedes: "bailan",
      yo: "bailo",
    },
    futur: {
      el: "bailará",
      nosotros: "bailaremos",
      tu: "bailarás",
      ustedes: "bailarán",
      yo: "bailaré",
    },
    imperf: {
      nosotros: "bailábamos",
      tu: "bailabas",
      ustedes: "bailaban",
      el: "bailaba",
      yo: "bailaba",
    },
  },
  besar: {
    translation: "To kiss",
    past: {
      el: "besó",
      tu: "besaste",
      ustedes: "besaron",
      nosotros: "besamos",
      yo: "besé",
    },
    pres: {
      el: "besa",
      nosotros: "besamos",
      tu: "besas",
      ustedes: "besan",
      yo: "beso",
    },
    futur: {
      el: "besará",
      nosotros: "besaremos",
      tu: "besarás",
      ustedes: "besarán",
      yo: "besaré",
    },
    imperf: {
      nosotros: "besábamos",
      tu: "besabas",
      ustedes: "besaban",
      el: "besaba",
      yo: "besaba",
    },
  },
  buscar: {
    translation: "To look for",
    past: {
      el: "buscó",
      tu: "buscaste",
      ustedes: "buscaron",
      nosotros: "buscamos",
      yo: "busqué",
    },
    pres: {
      el: "busca",
      nosotros: "buscamos",
      tu: "buscas",
      ustedes: "buscan",
      yo: "busco",
    },
    futur: {
      el: "buscará",
      nosotros: "buscaremos",
      tu: "buscarás",
      ustedes: "buscarán",
      yo: "buscaré",
    },
    imperf: {
      nosotros: "buscábamos",
      tu: "buscabas",
      ustedes: "buscaban",
      el: "buscaba",
      yo: "buscaba",
    },
  },
  caer: {
    translation: "To fall",
    past: {
      el: "cayó",
      nosotros: "caímos",
      tu: "caíste",
      ustedes: "cayeron",
      yo: "caí",
    },
    pres: {
      el: "cae",
      nosotros: "caemos",
      tu: "caes",
      ustedes: "caen",
      yo: "caigo",
    },
    futur: {
      el: "caerá",
      nosotros: "caeremos",
      tu: "caerás",
      ustedes: "caerán",
      yo: "caeré",
    },
    imperf: {
      nosotros: "caíamos",
      tu: "caías",
      ustedes: "caían",
      el: "caía",
      yo: "caía",
    },
  },
  caminar: {
    translation: "To walk",
    past: {
      el: "caminó",
      tu: "caminaste",
      ustedes: "caminaron",
      nosotros: "caminamos",
      yo: "caminé",
    },
    pres: {
      el: "camina",
      nosotros: "caminamos",
      tu: "caminas",
      ustedes: "caminan",
      yo: "camino",
    },
    futur: {
      el: "caminará",
      nosotros: "caminaremos",
      tu: "caminarás",
      ustedes: "caminarán",
      yo: "caminaré",
    },
    imperf: {
      nosotros: "caminábamos",
      tu: "caminabas",
      ustedes: "caminaban",
      el: "caminaba",
      yo: "caminaba",
    },
  },
  cantar: {
    translation: "To sing",
    past: {
      el: "cantó",
      tu: "cantaste",
      ustedes: "cantaron",
      nosotros: "cantamos",
      yo: "canté",
    },
    pres: {
      el: "canta",
      nosotros: "cantamos",
      tu: "cantas",
      ustedes: "cantan",
      yo: "canto",
    },
    futur: {
      el: "cantará",
      nosotros: "cantaremos",
      tu: "cantarás",
      ustedes: "cantarán",
      yo: "cantaré",
    },
    imperf: {
      nosotros: "cantábamos",
      tu: "cantabas",
      ustedes: "cantaban",
      el: "cantaba",
      yo: "cantaba",
    },
  },
  cerrar: {
    translation: "To close",
    past: {
      el: "cerró",
      tu: "cerraste",
      ustedes: "cerraron",
      nosotros: "cerramos",
      yo: "cerré",
    },
    pres: {
      el: "cierra",
      nosotros: "cerramos",
      tu: "cierras",
      ustedes: "cierran",
      yo: "cierro",
    },
    futur: {
      el: "cerrará",
      nosotros: "cerraremos",
      tu: "cerrarás",
      ustedes: "cerrarán",
      yo: "cerraré",
    },
    imperf: {
      nosotros: "cerrábamos",
      tu: "cerrabas",
      ustedes: "cerraban",
      el: "cerraba",
      yo: "cerraba",
    },
  },
  cocinar: {
    translation: "To cook",
    past: {
      el: "cocinó",
      tu: "cocinaste",
      ustedes: "cocinaron",
      nosotros: "cocinamos",
      yo: "cociné",
    },
    pres: {
      el: "cocina",
      nosotros: "cocinamos",
      tu: "cocinas",
      ustedes: "cocinan",
      yo: "cocino",
    },
    futur: {
      el: "cocinará",
      nosotros: "cocinaremos",
      tu: "cocinarás",
      ustedes: "cocinarán",
      yo: "cocinaré",
    },
    imperf: {
      nosotros: "cocinábamos",
      tu: "cocinabas",
      ustedes: "cocinaban",
      el: "cocinaba",
      yo: "cocinaba",
    },
  },
  comer: {
    translation: "To eat",
    past: {
      el: "comió",
      nosotros: "comimos",
      tu: "comiste",
      ustedes: "comieron",
      yo: "comí",
    },
    pres: {
      el: "come",
      nosotros: "comemos",
      tu: "comes",
      ustedes: "comen",
      yo: "como",
    },
    futur: {
      el: "comerá",
      nosotros: "comeremos",
      tu: "comerás",
      ustedes: "comerán",
      yo: "comeré",
    },
    imperf: {
      nosotros: "comíamos",
      tu: "comías",
      ustedes: "comían",
      el: "comía",
      yo: "comía",
    },
  },
  comprar: {
    translation: "To buy",
    past: {
      el: "compró",
      tu: "compraste",
      ustedes: "compraron",
      nosotros: "compramos",
      yo: "compré",
    },
    pres: {
      el: "compra",
      nosotros: "compramos",
      tu: "compras",
      ustedes: "compran",
      yo: "compro",
    },
    futur: {
      el: "comprará",
      nosotros: "compraremos",
      tu: "comprarás",
      ustedes: "comprarán",
      yo: "compraré",
    },
    imperf: {
      nosotros: "comprábamos",
      tu: "comprabas",
      ustedes: "compraban",
      el: "compraba",
      yo: "compraba",
    },
  },
  correr: {
    translation: "To run",
    past: {
      el: "corrió",
      nosotros: "corrimos",
      tu: "corriste",
      ustedes: "corrieron",
      yo: "corrí",
    },
    pres: {
      el: "corre",
      nosotros: "corremos",
      tu: "corres",
      ustedes: "corren",
      yo: "corro",
    },
    futur: {
      el: "correrá",
      nosotros: "correremos",
      tu: "correrás",
      ustedes: "correrán",
      yo: "correré",
    },
    imperf: {
      nosotros: "corríamos",
      tu: "corrías",
      ustedes: "corrían",
      el: "corría",
      yo: "corría",
    },
  },
  cortar: {
    translation: "To cut",
    past: {
      el: "cortó",
      tu: "cortaste",
      ustedes: "cortaron",
      nosotros: "cortamos",
      yo: "corté",
    },
    pres: {
      el: "corta",
      nosotros: "cortamos",
      tu: "cortas",
      ustedes: "cortan",
      yo: "corto",
    },
    futur: {
      el: "cortará",
      nosotros: "cortaremos",
      tu: "cortarás",
      ustedes: "cortarán",
      yo: "cortaré",
    },
    imperf: {
      nosotros: "cortábamos",
      tu: "cortabas",
      ustedes: "cortaban",
      el: "cortaba",
      yo: "cortaba",
    },
  },
  dar: {
    translation: "To give",
    past: {
      el: "dio",
      nosotros: "dimos",
      tu: "diste",
      ustedes: "dieron",
      yo: "di",
    },
    pres: {
      el: "da",
      nosotros: "damos",
      tu: "das",
      ustedes: "dan",
      yo: "doy",
    },
    futur: {
      el: "dará",
      nosotros: "daremos",
      tu: "darás",
      ustedes: "darán",
      yo: "daré",
    },
    imperf: {
      nosotros: "dábamos",
      tu: "dabas",
      ustedes: "daban",
      el: "daba",
      yo: "daba",
    },
  },
  deber: {
    translation: "To owe / should",
    past: {
      el: "debió",
      nosotros: "debimos",
      tu: "debiste",
      ustedes: "debieron",
      yo: "debí",
    },
    pres: {
      el: "debe",
      nosotros: "debemos",
      tu: "debes",
      ustedes: "deben",
      yo: "debo",
    },
    futur: {
      el: "deberá",
      nosotros: "deberemos",
      tu: "deberás",
      ustedes: "deberán",
      yo: "deberé",
    },
    imperf: {
      nosotros: "debíamos",
      tu: "debías",
      ustedes: "debían",
      el: "debía",
      yo: "debía",
    },
  },
  decir: {
    translation: "To say / tell",
    past: {
      el: "dijo",
      nosotros: "dijimos",
      tu: "dijiste",
      ustedes: "dijeron",
      yo: "dije",
    },
    pres: {
      el: "dice",
      nosotros: "decimos",
      tu: "dices",
      ustedes: "dicen",
      yo: "digo",
    },
    futur: {
      el: "dirá",
      nosotros: "diremos",
      tu: "dirás",
      ustedes: "dirán",
      yo: "diré",
    },
    imperf: {
      nosotros: "decíamos",
      tu: "decías",
      ustedes: "decían",
      el: "decía",
      yo: "decía",
    },
  },
  dibujar: {
    translation: "To draw",
    past: {
      el: "dibujó",
      tu: "dibujaste",
      nosotros: "dibujamos",
      ustedes: "dibujaron",
      yo: "dibujé",
    },
    pres: {
      el: "dibuja",
      nosotros: "dibujamos",
      tu: "dibujas",
      ustedes: "dibujan",
      yo: "dibujo",
    },
    futur: {
      el: "dibujará",
      nosotros: "dibujaremos",
      tu: "dibujarás",
      ustedes: "dibujarán",
      yo: "dibujaré",
    },
    imperf: {
      nosotros: "dibujábamos",
      tu: "dibujabas",
      ustedes: "dibujaban",
      el: "dibujaba",
      yo: "dibujaba",
    },
  },
  dormir: {
    translation: "To sleep",
    past: {
      el: "durmió",
      tu: "dormiste",
      ustedes: "durmieron",
      nosotros: "dormimos",
      yo: "dormí",
    },
    pres: {
      el: "duerme",
      nosotros: "dormimos",
      tu: "duermes",
      ustedes: "duermen",
      yo: "duermo",
    },
    futur: {
      el: "dormirá",
      nosotros: "dormiremos",
      tu: "dormirás",
      ustedes: "dormirán",
      yo: "dormiré",
    },
    imperf: {
      nosotros: "dormíamos",
      tu: "dormías",
      ustedes: "dormían",
      el: "dormía",
      yo: "dormía",
    },
  },
  entrar: {
    translation: "To enter",
    past: {
      el: "entró",
      tu: "entraste",
      nosotros: "entramos",
      ustedes: "entraron",
      yo: "entré",
    },
    pres: {
      el: "entra",
      nosotros: "entramos",
      tu: "entras",
      ustedes: "entran",
      yo: "entro",
    },
    futur: {
      el: "entrará",
      nosotros: "entraremos",
      tu: "entrarás",
      ustedes: "entrarán",
      yo: "entraré",
    },
    imperf: {
      nosotros: "entrábamos",
      tu: "entrabas",
      ustedes: "entraban",
      el: "entraba",
      yo: "entraba",
    },
  },
  esconder: {
    translation: "To hide",
    past: {
      el: "escondió",
      nosotros: "escondimos",
      tu: "escondiste",
      ustedes: "escondieron",
      yo: "escondí",
    },
    pres: {
      el: "esconde",
      nosotros: "escondemos",
      tu: "escondes",
      ustedes: "esconden",
      yo: "escondo",
    },
    futur: {
      el: "esconderá",
      nosotros: "esconderemos",
      tu: "esconderás",
      ustedes: "esconderán",
      yo: "esconderé",
    },
    imperf: {
      nosotros: "escondíamos",
      tu: "escondías",
      ustedes: "escondían",
      el: "escondía",
      yo: "escondía",
    },
  },
  esperar: {
    translation: "To hope / wait",
    past: {
      el: "esperó",
      tu: "esperaste",
      ustedes: "esperaron",
      nosotros: "esperamos",
      yo: "esperé",
    },
    pres: {
      el: "espera",
      nosotros: "esperamos",
      tu: "esperas",
      ustedes: "esperan",
      yo: "espero",
    },
    futur: {
      el: "esperará",
      nosotros: "esperaremos",
      tu: "esperarás",
      ustedes: "esperarán",
      yo: "esperaré",
    },
    imperf: {
      nosotros: "esperábamos",
      tu: "esperabas",
      ustedes: "esperaban",
      el: "esperaba",
      yo: "esperaba",
    },
  },
  gritar: {
    translation: "To scream / shout",
    past: {
      el: "gritó",
      tu: "gritaste",
      ustedes: "gritaron",
      nosotros: "gritamos",
      yo: "grité",
    },
    pres: {
      el: "grita",
      nosotros: "gritamos",
      tu: "gritas",
      ustedes: "gritan",
      yo: "grito",
    },
    futur: {
      el: "gritará",
      nosotros: "gritaremos",
      tu: "gritarás",
      ustedes: "gritarán",
      yo: "gritaré",
    },
    imperf: {
      nosotros: "gritábamos",
      tu: "gritabas",
      ustedes: "gritaban",
      el: "gritaba",
      yo: "gritaba",
    },
  },
  hacer: {
    translation: "To do / Make",
    past: {
      el: "hizo",
      nosotros: "hicimos",
      tu: "hiciste",
      ustedes: "hicieron",
      nosotros: "hacemos",
      yo: "hice",
    },
    pres: {
      el: "hace",
      nosotros: "hacemos",
      tu: "haces",
      ustedes: "hacen",
      yo: "hago",
    },
    futur: {
      el: "hará",
      nosotros: "haremos",
      tu: "harás",
      ustedes: "harán",
      yo: "haré",
    },
    imperf: {
      nosotros: "hacíamos",
      tu: "hacías",
      ustedes: "hacían",
      el: "hacía",
      yo: "hacía",
    },
  },
  ir: {
    translation: "To go",
    past: {
      el: "fue",
      nosotros: "fuimos",
      tu: "fuiste",
      ustedes: "fueron",
      yo: "fui",
    },
    pres: {
      el: "va",
      nosotros: "vamos",
      tu: "vas",
      ustedes: "van",
      yo: "voy",
    },
    futur: {
      el: "irá",
      nosotros: "iremos",
      tu: "irás",
      ustedes: "irán",
      yo: "iré",
    },
    imperf: {
      nosotros: "íbamos",
      tu: "ibas",
      ustedes: "iban",
      el: "iba",
      yo: "iba",
    },
  },
  jugar: {
    translation: "To play (a game or sport)",
    past: {
      el: "jugó",
      tu: "jugaste",
      ustedes: "jugaron",
      nosotros: "jugamos",
      yo: "jugué",
    },
    pres: {
      el: "juega",
      nosotros: "jugamos",
      tu: "juegas",
      ustedes: "juegan",
      yo: "juego",
    },
    futur: {
      el: "jugará",
      nosotros: "jugaremos",
      tu: "jugarás",
      ustedes: "jugarán",
      yo: "jugaré",
    },
    imperf: {
      nosotros: "jugábamos",
      tu: "jugabas",
      ustedes: "jugaban",
      el: "jugaba",
      yo: "jugaba",
    },
  },
  lavar: {
    translation: "To wash",
    past: {
      el: "lavó",
      tu: "lavaste",
      ustedes: "lavaron",
      nosotros: "lavamos",
      yo: "lavé",
    },
    pres: {
      el: "lava",
      nosotros: "lavamos",
      tu: "lavas",
      ustedes: "lavan",
      yo: "lavo",
    },
    futur: {
      el: "lavará",
      nosotros: "lavaremos",
      tu: "lavarás",
      ustedes: "lavarán",
      yo: "lavaré",
    },
    imperf: {
      nosotros: "lavábamos",
      tu: "lavabas",
      ustedes: "lavaban",
      el: "lavaba",
      yo: "lavaba",
    },
  },
  leer: {
    translation: "To read",
    past: {
      el: "leyó",
      nosotros: "leímos",
      tu: "leíste",
      ustedes: "leyeron",
      yo: "leí",
    },
    pres: {
      el: "lee",
      nosotros: "leemos",
      tu: "lees",
      ustedes: "leen",
      yo: "leo",
    },
    futur: {
      el: "leerá",
      nosotros: "leeremos",
      tu: "leerás",
      ustedes: "leerán",
      yo: "leeré",
    },
    imperf: {
      nosotros: "leíamos",
      tu: "leías",
      ustedes: "leían",
      el: "leía",
      yo: "leía",
    },
  },
  llorar: {
    translation: "To cry",
    past: {
      el: "lloró",
      tu: "lloraste",
      ustedes: "lloraron",
      nosotros: "lloramos",
      yo: "lloré",
    },
    pres: {
      el: "llora",
      nosotros: "lloramos",
      tu: "lloras",
      ustedes: "lloran",
      yo: "lloro",
    },
    futur: {
      el: "llorará",
      nosotros: "lloraremos",
      tu: "llorarás",
      ustedes: "llorarán",
      yo: "lloraré",
    },
    imperf: {
      nosotros: "llorábamos",
      tu: "llorabas",
      ustedes: "lloraban",
      el: "lloraba",
      yo: "lloraba",
    },
  },
  mirar: {
    translation: "To look",
    past: {
      el: "miró",
      tu: "miraste",
      ustedes: "miraron",
      nosotros: "miramos",
      yo: "miré",
    },
    pres: {
      el: "mira",
      nosotros: "miramos",
      tu: "miras",
      ustedes: "miran",
      yo: "miro",
    },
    futur: {
      el: "mirará",
      nosotros: "miraremos",
      tu: "mirarás",
      ustedes: "mirarán",
      yo: "miraré",
    },
    imperf: {
      nosotros: "mirábamos",
      tu: "mirabas",
      ustedes: "miraban",
      el: "miraba",
      yo: "miraba",
    },
  },
  morder: {
    translation: "To bite",
    past: {
      el: "mordió",
      nosotros: "mordimos",
      tu: "mordiste",
      ustedes: "mordieron",
      yo: "mordí",
    },
    pres: {
      el: "muerde",
      nosotros: "mordemos",
      tu: "muerdes",
      ustedes: "muerden",
      yo: "muerdo",
    },
    futur: {
      el: "morderá",
      nosotros: "morderemos",
      tu: "morderás",
      ustedes: "morderán",
      yo: "morderé",
    },
    imperf: {
      nosotros: "mordíamos",
      tu: "mordías",
      ustedes: "mordían",
      el: "mordía",
      yo: "mordía",
    },
  },
  nadar: {
    translation: "To swim",
    past: {
      el: "nadó",
      tu: "nadaste",
      ustedes: "nadaron",
      nosotros: "nadamos",
      yo: "nadé",
    },
    pres: {
      el: "nada",
      nosotros: "nadamos",
      tu: "nadas",
      ustedes: "nadan",
      yo: "nado",
    },
    futur: {
      el: "nadará",
      nosotros: "nadaremos",
      tu: "nadarás",
      ustedes: "nadarán",
      yo: "nadaré",
    },
    imperf: {
      nosotros: "nadábamos",
      tu: "nadabas",
      ustedes: "nadaban",
      el: "nadaba",
      yo: "nadaba",
    },
  },
  peinar: {
    translation: "To comb",
    past: {
      el: "peinó",
      tu: "peinaste",
      ustedes: "peinaron",
      nosotros: "peinamos",
      yo: "peiné",
    },
    pres: {
      el: "peina",
      nosotros: "peinamos",
      tu: "peinas",
      ustedes: "peinan",
      yo: "peino",
    },
    futur: {
      el: "peinará",
      nosotros: "peinaremos",
      tu: "peinarás",
      ustedes: "peinarán",
      yo: "peinaré",
    },
    imperf: {
      nosotros: "peinábamos",
      tu: "peinabas",
      ustedes: "peinaban",
      el: "peinaba",
      yo: "peinaba",
    },
  },
  poder: {
    translation: "To be able to",
    past: {
      el: "pudo",
      nosotros: "pudimos",
      tu: "pudiste",
      ustedes: "pudieron",
      yo: "pude",
    },
    pres: {
      el: "puede",
      nosotros: "podemos",
      tu: "puedes",
      ustedes: "pueden",
      yo: "puedo",
    },
    futur: {
      el: "podrá",
      nosotros: "podremos",
      tu: "podrás",
      ustedes: "podrán",
      yo: "podré",
    },
    imperf: {
      nosotros: "podíamos",
      tu: "podías",
      ustedes: "podían",
      el: "podía",
      yo: "podía",
    },
  },
  poner: {
    translation: "To put",
    past: {
      el: "puso",
      nosotros: "pusimos",
      tu: "pusiste",
      ustedes: "pusieron",
      yo: "puse",
    },
    pres: {
      el: "pone",
      nosotros: "ponemos",
      tu: "pones",
      ustedes: "ponen",
      yo: "pongo",
    },
    futur: {
      el: "pondrá",
      nosotros: "pondremos",
      tu: "pondrás",
      ustedes: "pondrán",
      yo: "pondré",
    },
    imperf: {
      nosotros: "poníamos",
      tu: "ponías",
      ustedes: "ponían",
      el: "ponía",
      yo: "ponía",
    },
  },
  prender: {
    translation: "To light / turn on",
    past: {
      el: "prendió",
      nosotros: "prendimos",
      tu: "prendiste",
      ustedes: "prendieron",
      yo: "prendí",
    },
    pres: {
      el: "prende",
      nosotros: "prendemos",
      tu: "prendes",
      ustedes: "prenden",
      yo: "prendo",
    },
    futur: {
      el: "prenderá",
      nosotros: "prenderemos",
      tu: "prenderás",
      ustedes: "prenderán",
      yo: "prenderé",
    },
    imperf: {
      nosotros: "prendíamos",
      tu: "prendías",
      ustedes: "prendían",
      el: "prendía",
      yo: "prendía",
    },
  },
  querer: {
    translation: "To want",
    past: {
      el: "quiso",
      nosotros: "quisimos",
      tu: "quisiste",
      ustedes: "quisieron",
      yo: "quise",
    },
    pres: {
      el: "quiere",
      nosotros: "queremos",
      tu: "quieres",
      ustedes: "quieren",
      yo: "quiero",
    },
    futur: {
      el: "querrá",
      nosotros: "querremos",
      tu: "querrás",
      ustedes: "querrán",
      yo: "querré",
    },
    imperf: {
      nosotros: "queríamos",
      tu: "querías",
      ustedes: "querían",
      el: "quería",
      yo: "quería",
    },
  },
  regalar: {
    translation: "To give",
    past: {
      el: "regaló",
      tu: "regalaste",
      nosotros: "regalamos",
      ustedes: "regalaron",
      yo: "regalé",
    },
    pres: {
      el: "regala",
      nosotros: "regalamos",
      tu: "regalas",
      ustedes: "regalan",
      yo: "regalo",
    },
    futur: {
      el: "regalará",
      nosotros: "regalaremos",
      tu: "regalarás",
      ustedes: "regalarán",
      yo: "regalaré",
    },
    imperf: {
      nosotros: "regalábamos",
      tu: "regalabas",
      ustedes: "regalaban",
      el: "regalaba",
      yo: "regalaba",
    },
  },
  romper: {
    translation: "To break",
    past: {
      el: "rompió",
      nosotros: "rompimos",
      tu: "rompiste",
      ustedes: "rompieron",
      yo: "rompí",
    },
    pres: {
      el: "rompe",
      nosotros: "rompemos",
      tu: "rompes",
      ustedes: "rompen",
      yo: "rompo",
    },
    futur: {
      el: "romperá",
      nosotros: "romperemos",
      tu: "romperás",
      ustedes: "romperán",
      yo: "romperé",
    },
    imperf: {
      nosotros: "rompíamos",
      tu: "rompías",
      ustedes: "rompían",
      el: "rompía",
      yo: "rompía",
    },
  },
  saber: {
    translation: "To know",
    past: {
      el: "supo",
      nosotros: "supimos",
      tu: "supiste",
      ustedes: "supieron",
      yo: "supe",
    },
    pres: {
      el: "sabe",
      nosotros: "sabemos",
      tu: "sabes",
      ustedes: "saben",
      yo: "sé",
    },
    futur: {
      el: "sabrá",
      nosotros: "sabremos",
      tu: "sabrás",
      ustedes: "sabrán",
      yo: "sabré",
    },
    imperf: {
      nosotros: "sabíamos",
      tu: "sabías",
      ustedes: "sabían",
      el: "sabía",
      yo: "sabía",
    },
  },
  salir: {
    translation: "To leave",
    past: {
      el: "salió",
      tu: "saliste",
      ustedes: "salieron",
      nosotros: "salimos",
      yo: "salí",
    },
    pres: {
      el: "sale",
      nosotros: "salimos",
      tu: "sales",
      ustedes: "salen",
      yo: "salgo",
    },
    futur: {
      el: "saldrá",
      nosotros: "saldremos",
      tu: "saldrás",
      ustedes: "saldrán",
      yo: "saldré",
    },
    imperf: {
      nosotros: "salíamos",
      tu: "salías",
      ustedes: "salían",
      el: "salía",
      yo: "salía",
    },
  },
  saltar: {
    translation: "To jump",
    past: {
      el: "saltó",
      tu: "saltaste",
      ustedes: "saltaron",
      nosotros: "saltamos",
      yo: "salté",
    },
    pres: {
      el: "salta",
      nosotros: "saltamos",
      tu: "saltas",
      ustedes: "saltan",
      yo: "salto",
    },
    futur: {
      el: "saltará",
      nosotros: "saltaremos",
      tu: "saltarás",
      ustedes: "saltarán",
      yo: "saltaré",
    },
    imperf: {
      nosotros: "saltábamos",
      tu: "saltabas",
      ustedes: "saltaban",
      el: "saltaba",
      yo: "saltaba",
    },
  },
  saludar: {
    translation: "To greet",
    past: {
      el: "saludó",
      tu: "saludaste",
      ustedes: "saludaron",
      nosotros: "saludamos",
      yo: "saludé",
    },
    pres: {
      el: "saluda",
      nosotros: "saludamos",
      tu: "saludas",
      ustedes: "saludan",
      yo: "saludo",
    },
    futur: {
      el: "saludará",
      nosotros: "saludaremos",
      tu: "saludarás",
      ustedes: "saludarán",
      yo: "saludaré",
    },
    imperf: {
      nosotros: "saludábamos",
      tu: "saludabas",
      ustedes: "saludaban",
      el: "saludaba",
      yo: "saludaba",
    },
  },
  sentir: {
    translation: "To feel",
    past: {
      el: "sintió",
      tu: "sentiste",
      ustedes: "sintieron",
      nosotros: "sentimos",
      yo: "sentí",
    },
    pres: {
      el: "siente",
      nosotros: "sentimos",
      tu: "sientes",
      ustedes: "sienten",
      yo: "siento",
    },
    futur: {
      el: "sentirá",
      nosotros: "sentiremos",
      tu: "sentirás",
      ustedes: "sentirán",
      yo: "sentiré",
    },
    imperf: {
      nosotros: "sentíamos",
      tu: "sentías",
      ustedes: "sentían",
      el: "sentía",
      yo: "sentía",
    },
  },
  soplar: {
    translation: "To blow",
    past: {
      el: "sopló",
      tu: "soplaste",
      ustedes: "soplaron",
      nosotros: "soplamos",
      yo: "soplé",
    },
    pres: {
      el: "sopla",
      nosotros: "soplamos",
      tu: "soplas",
      ustedes: "soplan",
      yo: "soplo",
    },
    futur: {
      el: "soplará",
      nosotros: "soplaremos",
      tu: "soplarás",
      ustedes: "soplarán",
      yo: "soplaré",
    },
    imperf: {
      nosotros: "soplábamos",
      tu: "soplabas",
      ustedes: "soplaban",
      el: "soplaba",
      yo: "soplaba",
    },
  },
  tocar: {
    translation: "To touch / play (an instrument)",
    past: {
      el: "tocó",
      tu: "tocaste",
      ustedes: "tocaron",
      nosotros: "tocamos",
      yo: "toqué",
    },
    pres: {
      el: "toca",
      nosotros: "tocamos",
      tu: "tocas",
      ustedes: "tocan",
      yo: "toco",
    },
    futur: {
      el: "tocará",
      nosotros: "tocaremos",
      tu: "tocarás",
      ustedes: "tocarán",
      yo: "tocaré",
    },
    imperf: {
      nosotros: "tocábamos",
      tu: "tocabas",
      ustedes: "tocaban",
      el: "tocaba",
      yo: "tocaba",
    },
  },
  traer: {
    translation: "To bring",
    past: {
      el: "trajo",
      nosotros: "trajimos",
      tu: "trajiste",
      ustedes: "trajeron",
      yo: "traje",
    },
    pres: {
      el: "trae",
      nosotros: "traemos",
      tu: "traes",
      ustedes: "traen",
      yo: "traigo",
    },
    futur: {
      el: "traerá",
      nosotros: "traeremos",
      tu: "traerás",
      ustedes: "traerán",
      yo: "traeré",
    },
    imperf: {
      nosotros: "traíamos",
      tu: "traías",
      ustedes: "traían",
      el: "traía",
      yo: "traía",
    },
  },
  venir: {
    translation: "To come",
    past: {
      el: "vino",
      nosotros: "vinimos",
      tu: "viniste",
      ustedes: "vinieron",
      yo: "vine",
    },
    pres: {
      el: "viene",
      nosotros: "venimos",
      tu: "vienes",
      ustedes: "vienen",
      yo: "vengo",
    },
    futur: {
      el: "vendrá",
      nosotros: "vendremos",
      tu: "vendrás",
      ustedes: "vendrán",
      yo: "vendré",
    },
    imperf: {
      nosotros: "veníamos",
      tu: "venías",
      ustedes: "venían",
      el: "venía",
      yo: "venía",
    },
  },
  ver: {
    translation: "To see",
    past: {
      el: "vio",
      nosotros: "vimos",
      tu: "viste",
      ustedes: "vieron",
      yo: "vi",
    },
    pres: {
      el: "ve",
      nosotros: "vemos",
      tu: "ves",
      ustedes: "ven",
      yo: "veo",
    },
    futur: {
      el: "verá",
      nosotros: "veremos",
      tu: "verás",
      ustedes: "verán",
      yo: "veré",
    },
    imperf: {
      nosotros: "veíamos",
      tu: "veías",
      ustedes: "veían",
      el: "veía",
      yo: "veía",
    },
  },
};

const infinitives = Object.keys(verbs);
// pt# we should grab the whole object?

const today = Date.now();
console.log('today : ', today );
const oneDay = 1000 * 60 * 60 * 24 // milli, sec, min, hour
console.log('oneDay : ', oneDay );
const todayDay = (today / oneDay).toFixed(0);
console.log('todayDay : ', todayDay );
const todaysIndex = todayDay % infinitives.length;
console.log('todaysIndex : ', todaysIndex );
const todaysVerb = infinitives[todaysIndex];

document.getElementById("word").innerHTML = todaysVerb || "oops!";

document.getElementById("pres_yo").innerHTML = verbs[todaysVerb].pres.yo;
document.getElementById("pres_tu").innerHTML = verbs[todaysVerb].pres.tu;
document.getElementById("pres_el").innerHTML = verbs[todaysVerb].pres.el;
document.getElementById("pres_nos").innerHTML = verbs[todaysVerb].pres.nosotros;
document.getElementById("pres_uds").innerHTML = verbs[todaysVerb].pres.ustedes;

document.getElementById("imperf_yo").innerHTML = verbs[todaysVerb].imperf.yo;
document.getElementById("imperf_tu").innerHTML = verbs[todaysVerb].imperf.tu;
document.getElementById("imperf_el").innerHTML = verbs[todaysVerb].imperf.el;
document.getElementById("imperf_nos").innerHTML =
  verbs[todaysVerb].imperf.nosotros;
document.getElementById("imperf_uds").innerHTML =
  verbs[todaysVerb].imperf.ustedes;

document.getElementById("past_yo").innerHTML = verbs[todaysVerb].past.yo;
document.getElementById("past_tu").innerHTML = verbs[todaysVerb].past.tu;
document.getElementById("past_el").innerHTML = verbs[todaysVerb].past.el;
document.getElementById("past_nos").innerHTML = verbs[todaysVerb].past.nosotros;
document.getElementById("past_uds").innerHTML = verbs[todaysVerb].past.ustedes;

document.getElementById("futur_yo").innerHTML = verbs[todaysVerb].futur.yo;
document.getElementById("futur_tu").innerHTML = verbs[todaysVerb].futur.tu;
document.getElementById("futur_el").innerHTML = verbs[todaysVerb].futur.el;
document.getElementById("futur_nos").innerHTML =
  verbs[todaysVerb].futur.nosotros;
document.getElementById("futur_uds").innerHTML =
  verbs[todaysVerb].futur.ustedes;

document.getElementById("definition").innerHTML = verbs[todaysVerb].translation;
